---
title: "complaints-flexdash"
author: "steph gemmell"
date: "3/28/2021"
output: html_document
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(kableExtra)
library(htmlwidgets)
library(htmltools)
library(readxl)


saveRDS(complaints, "complaints.rds")

not_timely <- complaints %>% 
  filter(timely_response == "No")

not_timely_freq <- complaints %>% 
  count(product)



joined2 <- joined %>% 
  select(
    name,
    salary2018 = salary.x,
    salary2019 = salary.y,
    title2018 = positiontitle.x,
    title2019 = positiontitle.y
    )

raises <- joined2 %>% 
  mutate(
    difference = (salary2019 - salary2018),
    pct_change = (difference/salary2018)
  ) %>% 
  select(
    name,
    salary2018,
    salary2019,
    difference,
    pct_change,
    title2018,
    title2019
  ) %>% 
  arrange(desc(pct_change))






```





2018-2019 Salaries Data 
=====================================
To filter, click on the boxes at the top of the columns. To sort, use the up/down arrows by the column names.


Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

salaries_table <- salaries %>% 
  select(
    year, first_mid = first_m, last, everything(),
    -name, -first, -paybasis #paybasis is the same per annum for everyone in the data
    ) %>% 
  mutate(
    year = as.factor(year),
    status = as.factor(status)
    ) %>% 
  arrange(
    desc(year),
    last,
    first_mid
  )


datatable(salaries_table,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons',
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy', 'csv', 'excel', 'print')
          )) %>%
      formatCurrency('salary', digits = 0) %>%
      formatStyle(c("last","first_mid", "salary"), fontWeight = 'bold') %>%
      # formatStyle("salary", color = "darkred") %>%
      formatStyle(
      'salary',
      background = styleColorBar(salaries_table$salary, 'steelblue'),
      backgroundSize = '100% 90%',
      backgroundRepeat = 'no-repeat',
      backgroundPosition = 'center'
    )


```




```{r}

datatable(raises,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons', 
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip',
       buttons = c('copy', 'csv', 'excel', 'print')
          )) %>% 
      formatCurrency(c("salary2018", "salary2019", "difference"), digits = 0) %>% 
      formatStyle(c("name", "difference", "pct_change"), fontWeight = 'bold') %>% 
      formatPercentage("pct_change") %>% 
      formatStyle(c("difference", "pct_change"), color = "darkgreen") 



```

